---
version: '3'
services:
  jenkins:
    container_name: my_jenkins
    image: jenkins-with-go
    build:
      context: ./
      dockerfile: Dockerfile
    environment:  
     - JAVA_OPTS=-Djava.awt.headless=true
     - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # skip setup wizard
    ports:
      - "80:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: always
